/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:cafe': typeof import('~icons/carbon/cafe')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    CheckIcon: typeof import('./app/components/icons/CheckIcon.vue')['default']
    CopyIcon: typeof import('./app/components/icons/CopyIcon.vue')['default']
    Expand: typeof import('./app/components/Expand.vue')['default']
    Footer: typeof import('./app/components/Footer.vue')['default']
    HeadlessToast: typeof import('./app/components/HeadlessToast.vue')['default']
    HeadlessToastWithProps: typeof import('./app/components/HeadlessToastWithProps.vue')['default']
    Hero: typeof import('./app/components/Hero.vue')['default']
    Installation: typeof import('./app/components/Installation.vue')['default']
    'Mdi:heart': typeof import('~icons/mdi/heart')['default']
    Others: typeof import('./app/components/Others.vue')['default']
    Position: typeof import('./app/components/Position.vue')['default']
    Styling: typeof import('./app/components/Styling.vue')['default']
    Theming: typeof import('./app/components/Theming.vue')['default']
    Types: typeof import('./app/components/Types.vue')['default']
    Usage: typeof import('./app/components/Usage.vue')['default']
  }
}
