// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Carbon:cafe': typeof import('~icons/carbon/cafe')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    Expand: typeof import('./src/components/Expand.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HeadlessToast: typeof import('./src/components/HeadlessToast.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Installation: typeof import('./src/components/Installation.vue')['default']
    'Mdi:heart': typeof import('~icons/mdi/heart')['default']
    Others: typeof import('./src/components/Others.vue')['default']
    Position: typeof import('./src/components/Position.vue')['default']
    Types: typeof import('./src/components/Types.vue')['default']
    Usage: typeof import('./src/components/Usage.vue')['default']
  }
}
