name: Publish commit with pkr-pr-new

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:lib

      - name: Publish
        run: pnpx pkg-pr-new publish
